<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-KBPQ0KS" name="com.testcases.LoginPageTest" tests="5" failures="0" timestamp="2021-11-22T15:03:25 IST" time="88.907" errors="1">
  <testcase name="validateLoginUsingTestNGProvider" time="88.905" classname="com.testcases.LoginPageTest"/>
  <system-out/>
  <testcase name="GenerateReport" time="0.002" classname="com.testcases.LoginPageTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.base.TestBase.CloseReportSetup(TestBase.java:66)
at com.testcases.LoginPageTest.GenerateReport(LoginPageTest.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.afterRun(TestRunner.java:877)
at org.testng.TestRunner.run(TestRunner.java:599)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- GenerateReport -->
  <system-out/>
  <testcase name="validateLoginTestUsingParameters" classname="com.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- validateLoginTestUsingParameters -->
  <system-out/>
  <testcase name="validateTitleTest" classname="com.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- validateTitleTest -->
  <system-out/>
  <testcase name="validateLoginTest" classname="com.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- validateLoginTest -->
  <system-out/>
</testsuite> <!-- com.testcases.LoginPageTest -->
